### ISSUE TITLE
Not working on windows 11

### ISSUE THREAD

**Issue by d78ui98** [evilpan/gptcli#25]
I am trying to run gptcli on windows 11.

Here is the error I am facing

```
(venv) PS D:\experiments\gptcli-main\gptcli-main> python .\gptcli.py -c .\config.json
Loading config from: .\config.json
openai.api_key=sk-mEkw*****
openai.api_base=https://chat.pppan.net/v1
openai.api_type=open_ai
openai.api_version=None
openai.api_organization=None
Proxy: socks5://localhost:1080
Context level: ContextLevel.FULL
Stream mode: True
gptcli> hello
Traceback (most recent call last):
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 252, in query_openai_stream
    response = openai.ChatCompletion.create(
  File "D:\experiments\gptcli-main\gptcli-main\venv\lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 420, in <module>
    main()
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 417, in main
    app.cmdloop()
  File "D:\experiments\gptcli-main\gptcli-main\venv\lib\site-packages\cmd2\cmd2.py", line 5285, in cmdloop
    self._cmdloop()
  File "D:\experiments\gptcli-main\gptcli-main\venv\lib\site-packages\cmd2\cmd2.py", line 3142, in _cmdloop
    stop = self.onecmd_plus_hooks(line)
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 131, in onecmd_plus_hooks
    self.handle_input(line)
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 163, in handle_input
    answer = self.query_openai_stream(self.messages)
  File "D:\experiments\gptcli-main\gptcli-main\gptcli.py", line 272, in query_openai_stream
    except openai.error.OpenAIError as e:
AttributeError: module 'openai' has no attribute 'error'
```

Let me know if any more information is required from my side.

**Comment by evilpan** [comment]
Thanks for reporting this problem! Seems that the openai's python API has changed, please try fix the openai version by running `pip3 install openai==0.28`, The `requirements.txt` is also updated now.

**Comment by d78ui98** [comment]
Thank you for your quick support and for updating the requirements.txt
However I not sure why I am facing this new error
```
gptcli> hello
OpenAIError: Error communicating with OpenAI: SOCKSHTTPSConnectionPool(host='chat.pppan.net', port=443): Max retries
exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection
object at 0x00000239A88906D0>: Failed to establish a new connection: [WinError 10061] No connection could be made
because the target machine actively refused it'))
```

**Comment by evilpan** [comment]
If you can access api.openai.com directly, just clear the `proxy` option in `config.json`, the default config.json use `socks5://localhost:1080` as default proxy for some network restrictions.

further more, you can set `api_base` in `config.json` to `https://api.openai.com/v1`, this option is also used to workaround  network issues.

**Comment by d78ui98** [comment]
Thank you for your support. It is working as expected now. 
We can close this issue :)
